// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBz5UutN3dlGBAJP-bXJ9BRPiDM0YmalM',
    appId: '1:387722079834:web:3ad24e72fdc6ce05f6b263',
    messagingSenderId: '387722079834',
    projectId: 'voteapp-1cbe3',
    authDomain: 'voteapp-1cbe3.firebaseapp.com',
    storageBucket: 'voteapp-1cbe3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg_ssolsB6-RYF3Li2IqRVW3Sayy-DV3Q',
    appId: '1:387722079834:android:769100669713abb5f6b263',
    messagingSenderId: '387722079834',
    projectId: 'voteapp-1cbe3',
    storageBucket: 'voteapp-1cbe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD452EtsYbWQxe12M7wsB53TsP7H2z_WOg',
    appId: '1:387722079834:ios:1d05083118e4562ef6b263',
    messagingSenderId: '387722079834',
    projectId: 'voteapp-1cbe3',
    storageBucket: 'voteapp-1cbe3.firebasestorage.app',
    iosBundleId: 'com.example.voteApp',
  );
}
